version: "3.9"
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=SmartCityCluster

  backend:
    build: ./backend
    container_name: backend_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - cassandra

  frontend:
    build: ./frontend
    container_name: frontend_ui
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
